# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19e606d3d24c7e4c35c405f90082b250"
name = "admin-action-app"
handle = "admin-action-app-3"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "andyyfashion.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
